name: Envrionment Variable Workflow

on: [push]

env:
  WF_ENV: String Available to All jobs # this value is going to be available to all Jobs
  SECRET_ENV_VARIABLE: ${{secrets.WF_ENV}}
  GITHUB_TOKEN: ${{secrets.TOKEN}}

jobs:
  log-environment-variables:
    runs-on: ubuntu-latest
    env:
      JOB_ENV: String available to only this job # available to this job only
    steps:
      - name: Log Env
        env:
          STEP_ENV: Available only to this step
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
          echo "SECRET_ENV_VARIABLE: ${SECRET_ENV_VARIABLE}"
          echo "GITHUB_TOKEN : ${GITHUB_TOKEN}"

      - name: Another Step in the job
        run: |
          echo "WF_ENV: ${WF_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"

  log-default-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Default Envrionment Variable
        run: |
          echo "HOME :${HOME}"
          echo "GITHUB_WORKFLOW :${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS :${GITHUB_ACTION}"
          echo "GITHUB_ACTIONS :${GITHUB_ACTIONS}"
          echo "GITHUB_REPOSITORY :${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME :${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE :${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA :${GITHUB_SHA}"
          echo "GITHUB_REF :${GITHUB_REF}"
          echo "WF_ENV: ${WF_ENV}"
          echo "STEP_ENV: ${STEP_ENV}"
          echo "JOB_ENV: ${JOB_ENV}"
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail
