name: Simple Github Workflow

on: [push]

jobs:
  run-a-shell-command:
    runs-on:  ubuntu-20.04
    steps:
      - name: echo a string 
        run:  whoami
      - name: running a multiline command 
        run: | 
          whoami
          echo "General Zod" 
  run-windows-commands:
    runs-on:  windows-latest
    steps:
      - name: print current directory
        run: Get-Location 
      - name: Running a Bash Command on Windows Machine
        run: pwd
        shell: bash         